version: 2

# Specify the Python version and dependencies
python:
  version: 3.9
  install:
    - method: pip
      path: .
    - requirements: requirements.txt  # Add this if you have a requirements file

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py

# Build options
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"